services:
  - type: web
    name: sms-webhook
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python sms_webhook.py
    plan: free
    envVars:
      - key: RC_CLIENT_ID
        value: ZHAfEyW09wnbYKPCoo602y
      - key: RC_CLIENT_SECRET
        value: 4h078v61NPWcLILi24vh58bDOQhHLN44PcygwYrrnyx8
      - key: RC_JWT
        value: eyJraWQiOiI4NzYy...
      - key: ZOHO_CLIENT_ID
        value: your_zoho_client_id
      - key: ZOHO_CLIENT_SECRET
        value: your_zoho_client_secret
      - key: ZOHO_REFRESH_TOKEN
        value: your_refresh_token
      - key: RC_FROM_NUMBER
        value: +12014096774  # or whatever number works
